// API publica del feature catalog. Fuera del feature, importa solo desde aqui.
export { default as CategoriesManager } from './components/CategoriesManager.vue'
export { default as CategoryForm } from './components/CategoryForm.vue'
export { default as CategorySelect } from './components/CategorySelect.vue'
export { default as ColorForm } from './components/ColorForm.vue'
export { default as ColorsManager } from './components/ColorsManager.vue'
export { default as ColorSwatch } from './components/ColorSwatch.vue'
export { default as SizeForm } from './components/SizeForm.vue'
export { default as SizesManager } from './components/SizesManager.vue'
export { default as TaxesManager } from './components/TaxesManager.vue'
export { useCategoriesStore } from './stores/categories.store'
export { useColorsStore } from './stores/colors.store'
export { useSizesStore } from './stores/sizes.store'
export { useTaxesStore } from './stores/taxes.store'
export type { Category, CategoryRef, Color, Size, TaxConfig } from './types'
